# Generated by Django 5.2.14 on 2026-06-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=1999, help_text='Monthly subscription rate', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=500, help_text='Per hour rate (if applicable)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trainersession',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Monthly subscription amount', max_digits=10),
        ),
    ]
