# Generated by assistant to add position field and initialize values
from django.db import migrations, models


def set_positions(apps, schema_editor):
    Trainer = apps.get_model('trainers', 'Trainer')
    # Order trainers by featured and rating to assign sensible initial positions
    qs = list(Trainer.objects.order_by('-is_featured', '-average_rating'))
    for i, t in enumerate(qs, start=1):
        t.position = i
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_monthly_rate_alter_trainer_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='position',
            field=models.PositiveIntegerField(default=0, db_index=True),
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['position', '-is_featured', '-average_rating']},
        ),
        migrations.RunPython(set_positions, migrations.RunPython.noop),
    ]
