# Generated by Django 5.2.14 on 2026-06-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_add_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('cardio', 'Cardio'), ('strength_training', 'Strength Training'), ('yoga', 'Yoga'), ('nutrition', 'Nutrition'), ('general_fitness', 'General Fitness')], max_length=50),
        ),
    ]
