services:
  api:
    image: python:3.11-slim
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - SITE_URL=${SITE_URL}
    command: sh -c "python manage.py migrate && gunicorn fitzone.wsgi:application --bind 0.0.0.0:8000 --workers 2"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
