# Generated by Django 5.2.14 on 2026-06-13 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_type', models.CharField(choices=[('workout', 'Workout Badge'), ('streak', 'Streak Badge'), ('weight', 'Weight Goal Badge'), ('membership', 'Membership Badge'), ('social', 'Social Badge'), ('special', 'Special Badge')], max_length=20)),
                ('difficulty', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='bronze', max_length=20)),
                ('icon', models.CharField(default='fas fa-medal', max_length=50)),
                ('requirement_value', models.IntegerField(help_text='Number of actions required to earn this badge')),
                ('requirement_unit', models.CharField(blank=True, help_text='e.g., workouts, days, kg', max_length=50)),
                ('points', models.IntegerField(default=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['difficulty', 'requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_workouts', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_calories', models.IntegerField(default=0)),
                ('total_minutes', models.IntegerField(default=0)),
                ('weight_logged_count', models.IntegerField(default=0)),
                ('weight_lost_total', models.FloatField(default=0)),
                ('weight_gained_total', models.FloatField(default=0)),
                ('membership_days', models.IntegerField(default=0)),
                ('total_payments', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trainer_sessions', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
