# Generated by Django 5.2.14 on 2026-06-14 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message_type', models.CharField(choices=[('contact', 'Contact Us'), ('support', 'Contact Support'), ('report', 'Report Problem')], default='contact', max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('problem_type', models.CharField(blank=True, max_length=50)),
                ('steps_to_reproduce', models.TextField(blank=True)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('device_info', models.CharField(blank=True, max_length=500)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('read', 'Read'), ('replied', 'Replied'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Message',
                'verbose_name_plural': 'Support Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
