# Generated by Django 5.2.14 on 2026-06-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='admin_dashb_timesta_c85d92_idx',
            old_name='admin_dash_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='admin_dashb_action_fea09f_idx',
            old_name='admin_dash_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='admin_dashb_admin_u_d25e1c_idx',
            old_name='admin_dash_admin_idx',
        ),
    ]
