# Generated by Django 5.2.14 on 2026-06-13 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('custom', 'Custom')], max_length=20)),
                ('target_weight', models.FloatField(blank=True, help_text='Target weight in kg', null=True)),
                ('target_body_fat', models.FloatField(blank=True, help_text='Target body fat percentage', null=True)),
                ('target_date', models.DateField(blank=True, help_text='Date to achieve this goal', null=True)),
                ('weekly_workout_goal', models.IntegerField(default=3, help_text='Workouts per week')),
                ('weekly_calorie_goal', models.IntegerField(default=2000, help_text='Daily calorie target')),
                ('is_active', models.BooleanField(default=True)),
                ('achieved', models.BooleanField(default=False)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_goal_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fitness Goal',
                'verbose_name_plural': 'Fitness Goals',
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration_minutes', models.IntegerField()),
                ('calories_burned', models.IntegerField()),
                ('exercises_completed', models.TextField(blank=True, help_text='List of exercises done')),
                ('notes', models.TextField(blank=True)),
                ('felt_difficulty', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FitnessProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('body_fat_percentage', models.FloatField(blank=True, help_text='Body fat percentage', null=True)),
                ('chest', models.FloatField(blank=True, help_text='Chest measurement in cm', null=True)),
                ('waist', models.FloatField(blank=True, help_text='Waist measurement in cm', null=True)),
                ('hips', models.FloatField(blank=True, help_text='Hips measurement in cm', null=True)),
                ('biceps', models.FloatField(blank=True, help_text='Biceps measurement in cm', null=True)),
                ('thighs', models.FloatField(blank=True, help_text='Thighs measurement in cm', null=True)),
                ('resting_heart_rate', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fitness Progress',
                'ordering': ['-date_recorded'],
                'unique_together': {('user', 'date_recorded')},
            },
        ),
    ]
