# Generated by Django 5.2.14 on 2026-06-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_newslettersubscriber_subscribed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('welcome', 'Welcome Email'), ('payment_success', 'Payment Success'), ('membership_expiry', 'Membership Expiry'), ('booking_confirmation', 'Booking Confirmation'), ('workout_reminder', 'Workout Reminder'), ('password_reset', 'Password Reset'), ('account_deactivated', 'Account Deactivated'), ('account_reactivated', 'Account Reactivated'), ('account_deleted', 'Account Deleted'), ('account_deleted_admin', 'Account Deleted by Admin'), ('account_recovered', 'Account Recovered'), ('test', 'Test Email')], max_length=50),
        ),
    ]
